// type: 'single' (pick one) or 'multi' (select all that apply)
// correct: option indices as a sorted string, e.g. "1" or "0123"
// roomP: expected room accuracy (used only by monkey sizing)
// why: optional one-line explanation shown at reveal
export const QUESTIONS = [
  { id: 1, tag: "Philippines", type: "single", roomP: 0.55,
    text: "A trade body known as the PCA lobbied for its country\u2019s biodiesel mandate to rise from B3 to B5. Which PCA?",
    options: ["Pakistan Cotton Association", "Peruvian Cane Authority", "Philippine Coconut Authority", "Polish Canola Association"], correct: "2" },
  { id: 2, tag: "UK / RTFO", type: "single", roomP: 0.55,
    text: "In 2024, 29% of the UK\u2019s verified supply of a particular biofuel was made from a feedstock coined ULDUR. Which biofuel?",
    options: ["Biodiesel (FAME)", "Biomethane", "Ethanol", "HVO"], correct: "2" },
  { id: 3, tag: "UK / RTFO", type: "single", roomP: 0.40,
    text: "Most UK development-fuel RTFCs in 2025 went to biomethane-derived road fuels: diesel and petrol made by co-processing biomethane at refineries.",
    options: ["True", "False"], correct: "0" },
  { id: 4, tag: "UK SAF", type: "single", roomP: 0.40,
    text: "Under the UK SAF Mandate as legislated, the HEFA cap and the PtL obligation start in:",
    options: ["2027 and 2027", "2028 and 2028", "2028 and 2030", "2027 and 2028"], correct: "3" },
  { id: 5, tag: "UK ETS", type: "single", roomP: 0.35,
    text: "Under the UK ETS, which types of SAF can aircraft operators currently zero-rate?",
    options: ["Biofuel, PtL and RCF SAF", "Biofuel and PtL SAF", "Biofuel SAF only", "None: SAF is treated like fossil kerosene"], correct: "2" },
  { id: 6, tag: "RED / Annex III", type: "single", roomP: 0.45,
    text: "Under RED Annex III, what share of typical bio-ETBE and bio-MTBE respectively counts as renewable, measured by energy content?",
    options: ["22% / 37%", "37% / 22%", "55% / 45%", "100% / 100%"], correct: "1" },
  { id: 7, tag: "Ireland / RTFO", type: "single", roomP: 0.40,
    text: "Under the Irish RTFO, POME-based HVO earns Green certificates as an Annex IX Part A fuel. Since 1 July 2025 it earns, per MJ:",
    options: ["1 Green Certificate", "2 Green Certificates", "2.5 Green Certificates", "3 Green Certificates"], correct: "1" },
  { id: 8, tag: "EU ETS2 / BEHG", type: "single", roomP: 0.55,
    text: "Both of the following are true: the start of EU ETS2 was pushed from 2027 to 2028, and Germany decided to keep the BEHG price corridor of \u20ac55-65/tCO\u2082 for 2027.",
    options: ["True", "False"], correct: "0",
    why: "True. And it pays biofuels twice: sustainable biofuels carry an emission factor of zero under the BEHG, so no nEZ certificates are surrendered for them. The 2026 auctions were oversubscribed many times over and cleared at the \u20ac65 cap, so anything a supplier needs beyond its pro-rata fill is bought in the post-auction sale at \u20ac68. The marginal tonne of CO\u2082e displaced by biofuel therefore saves a \u20ac68 certificate, on top of its THG-Quote value." },
  { id: 9, tag: "SAF / cross-border", type: "single", roomP: 0.40,
    text: "A SAF produced by alcohol-to-jet from corn-grain ethanol achieves a 140% GHG saving on each scheme\u2019s own methodology. Assuming it meets all other requirements, it is eligible under:",
    options: ["All four: the UK SAF Mandate, ReFuelEU Aviation, CORSIA and US 45Z", "The UK SAF Mandate and ReFuelEU Aviation only", "None of them", "CORSIA and US 45Z only"], correct: "3" },
  { id: 10, tag: "Germany / THG", type: "single", roomP: 0.55,
    text: "A German quota-obligated party misses its THG-Quote. What is the penalty (P\u00f6nale) per tonne of CO\u2082e not abated?",
    options: ["\u20ac500", "\u20ac600", "\u20ac900", "\u20ac1,000"], correct: "1" },
  { id: 11, tag: "ABP / Annex IX", type: "single", roomP: 0.40,
    text: "Which ONE of the following is true of Category 3 animal fats, as classified under Regulation 1069/2009?",
    options: ["They may be used in animal feed in the EU", "They are subject to the RED Annex IX Part B cap", "They count towards the RED food and feed crop cap", "They are treated as an Annex IX Part A (advanced) feedstock in Finland"], correct: "0" },
  { id: 12, tag: "NL / EREs", type: "single", roomP: 0.30,
    text: "A barge loads 600 mt fossil naphtha, 200 mt ISCC PLUS circular naphtha and 200 mt ISCC EU bio-naphtha into one tank. The trader discharges 200 mt as circular naphtha at the first port, brings the remaining 800 mt into the Netherlands and applies to book 200 mt of bio-naphtha for EREs, the Dutch renewable-fuel units. Can the full 200 mt be booked?",
    options: ["Yes", "No"], correct: "1" },
  { id: 13, tag: "IR 2022/996", type: "multi", roomP: 0.30,
    text: "The draft revision of Implementing Regulation 2022/996 that was circulated to member states for comments in Q1 2026 includes:",
    options: ["Retroactive cancellation of Proofs of Sustainability (PoS) through the supply chain", "A six-month audit cycle for traders, down from twelve", "A one-month mass-balance period for traders", "A maximum of three years with the same certification body"], correct: "0123" },
  { id: 14, tag: "Norway", type: "single", roomP: 0.35,
    text: "Norway\u2019s road-fuel blending obligation (the omsetningskrav) currently applies the biofuel sustainability criteria of:",
    options: ["RED I (2009)", "RED II (2018)", "RED III (2023)", "Purely national criteria"], correct: "0" },
  { id: 15, tag: "Maritime", type: "single", roomP: 0.30,
    text: "Rapeseed methyl ester, a food-crop biodiesel, is bunkered into a ship. Which of these give it a renewable benefit rather than treating it as fossil?",
    options: ["EU ETS and UK ETS only", "FuelEU Maritime, EU ETS and UK ETS", "EU ETS, UK ETS and the IMO Net-Zero Framework as approved at MEPC 83", "All of them: FuelEU Maritime, EU ETS, UK ETS, the Dutch ZREs and the IMO framework"], correct: "2" },
  { id: 16, tag: "Canada", type: "single", roomP: 0.50,
    text: "A biofuel with a carbon intensity of 60 gCO\u2082e/MJ is supplied in British Columbia. The same physical litres can earn credits under both the BC LCFS and Canada\u2019s federal Clean Fuel Regulations.",
    options: ["True", "False"], correct: "0",
    why: "Yes. Under the BC LCFS any fuel below the 2026 diesel-class target of about 75 gCO\u2082e/MJ earns credits, and under the federal CFR any fuel below the 2026 diesel limit of 85 gCO\u2082e/MJ earns credits. The two programmes are independent, so the credits stack." },
  { id: 17, tag: "UK SAF", type: "single", roomP: 0.30,
    text: "A recycled carbon fuel (RCF) SAF has a UK-methodology CI of -35.6 gCO\u2082e/MJ, a 140% saving. Under the UK SAF Mandate, each litre earns approximately:",
    options: ["Nothing", "1 HEFA certificate", "2 HEFA certificates", "1 Main (non-HEFA) certificate", "2 Main (non-HEFA) SAF certificates", "2 PtL certificates"], correct: "4" },
  { id: 18, tag: "US / RFS", type: "single", roomP: 0.45,
    text: "Under the US RFS, if a Q-RIN (a RIN verified under an EPA-approved Quality Assurance Plan) later proves invalid, the RIN generator has an affirmative defence and the Q-RIN does not need to be replaced.",
    options: ["True", "False"], correct: "1" },
  { id: 19, tag: "UK / RTFO", type: "single", roomP: 0.30,
    text: "e-Ethanol, an RFNBO, is supplied as marine fuel for a UK domestic voyage. Under the RTFO it earns, per litre equivalent, and under the UK ETS the e-ethanol is treated as:",
    options: ["Nothing / fossil emission factor", "1 RTFC / fossil emission factor", "2 dRTFCs / fossil emission factor", "2 RTFCs / zero-rated"], correct: "3" },
  { id: 20, tag: "Germany / 37. BImSchV", type: "single", roomP: 0.40,
    text: "Under Germany\u2019s 37. BImSchV intermediate-product (Zwischenprodukt) pathway, e-methanol used to transesterify FAME has its energy content credited as RFNBO, while the FAME\u2019s CI is calculated as if fossil methanol had been used.",
    options: ["True", "False"], correct: "0" },
  { id: 21, tag: "Germany / THG", type: "single", roomP: 0.25,
    text: "Which of these can currently NOT earn credit under Germany\u2019s THG-Quote after the 2026 amendment of the BImSchG?",
    options: ["RFNBO supplied to the aviation market", "e-Methanol used as an intermediate in German FAME production", "Green hydrogen used as an intermediate in a German refinery\u2019s fossil-fuel production", "e-Methane supplied as LNG/CNG to international bunkering, with the supplier opting into domestic energy tax"], correct: "0" },
];
export const N_ROUNDS = QUESTIONS.length;
