// type: 'single' (pick one) or 'multi' (select all that apply)
// correct: option indices as a sorted string, e.g. "1" or "0123"
// roomP: expected room accuracy (used only by monkey sizing)
// source: optional citation shown at reveal
export const QUESTIONS = [
  { id: 1, tag: "Philippines", type: "single", roomP: 0.55,
    text: "A trade body known as the PCA lobbied for its country\u2019s biodiesel mandate to rise from B3 to B5. Which PCA?",
    options: ["Pakistan Cotton Association", "Peruvian Cane Authority", "Philippine Coconut Authority", "Polish Canola Association"], correct: "2",
    source: "PCA statement, Aug 2026" },
  { id: 2, tag: "UK / RTFO", type: "single", roomP: 0.55,
    text: "In 2024, 29% of the UK\u2019s verified supply of a particular biofuel was made from a feedstock coined ULDUR. Which biofuel?",
    options: ["Biodiesel (FAME)", "Biomethane", "Ethanol", "HVO"], correct: "2",
    source: "DfT RTFO statistics 2024" },
  { id: 3, tag: "UK SAF", type: "single", roomP: 0.40,
    text: "Under the UK SAF Mandate as legislated, the HEFA cap and the PtL obligation start in:",
    options: ["2027 and 2027", "2028 and 2028", "2028 and 2030", "2027 and 2028"], correct: "3",
    source: "DfT SAF Mandate guidance" },
  { id: 4, tag: "RED / Annex III", type: "single", roomP: 0.45,
    text: "Under RED Annex III, what share of typical bio-ETBE and bio-MTBE respectively counts as renewable, measured by energy content?",
    options: ["22% / 37%", "37% / 22%", "55% / 45%", "100% / 100%"], correct: "1",
    source: "RED II Annex III" },
  { id: 5, tag: "Ireland / RTFO", type: "single", roomP: 0.40,
    text: "Under the Irish RTFO, POME-based HVO earns Green certificates as an Annex IX Part A fuel. Since 1 July 2025 it earns, per MJ:",
    options: ["1 Green Certificate", "2 Green Certificates", "2.5 Green Certificates", "3 Green Certificates"], correct: "1",
    source: "S.I. No. 247 of 2025" },
  { id: 6, tag: "Germany / BEHG", type: "single", roomP: 0.40,
    text: "In 2026, when a fossil fuel is replaced with an eligible biofuel in Germany, the obligated party saves, per tonne of CO\u2082e that would otherwise have been obligated under the BEHG, approximately:",
    options: ["Nothing: the BEHG was replaced by EU ETS2 in 2026", "\u20ac60 per tCO\u2082e", "\u20ac65 per tCO\u2082e", "\u20ac68 per tCO\u2082e"], correct: "3",
    source: "BEHV \u00a7\u00a711\u201315" },
  { id: 7, tag: "SAF / cross-border", type: "single", roomP: 0.40,
    text: "A SAF produced by alcohol-to-jet from conventional corn-grain ethanol achieves a 140% GHG saving on each scheme\u2019s own methodology. It may be eligible under:",
    options: ["The UK SAF Mandate and ReFuelEU Aviation only", "CORSIA and US 45Z only", "All four: the UK SAF Mandate, ReFuelEU Aviation, CORSIA and US 45Z", "None of them"], correct: "1",
    source: "UK SAF Mandate Order; ReFuelEU Art. 3; CORSIA SCS; 26 U.S.C. \u00a745Z" },
  { id: 8, tag: "Germany / THG", type: "single", roomP: 0.55,
    text: "A German obligated party misses its THG-Quote on the general quota (\u201cTHG-Other\u201d, not the advanced or RFNBO sub-quotas). What is the penalty per tonne of CO\u2082e not abated?",
    options: ["\u20ac235", "\u20ac400", "\u20ac600", "\u20ac900"], correct: "2",
    source: "\u00a737c BImSchG; Argus Biofuels, 11 September 2026" },
  { id: 9, tag: "UK / RTFO", type: "single", roomP: 0.40,
    text: "Most UK development-fuel RTFCs in 2025 went to biomethane-derived road fuels: diesel and petrol made by co-processing biomethane at refineries.",
    options: ["True", "False"], correct: "0",
    source: "DfT RTFO statistics 2025" },
  { id: 10, tag: "ABP / Annex IX", type: "single", roomP: 0.40,
    text: "Which ONE of the following is true of Category 3 animal fats, as classified under Regulation 1069/2009?",
    options: ["They may be used in animal feed in the EU", "They are subject to the RED Annex IX Part B cap", "They count towards the RED food and feed crop cap", "They are treated as an Annex IX Part A (advanced) feedstock in Finland"], correct: "0",
    source: "Reg. 1069/2009; RED Annex IX Part B; Argus Biofuels, 5 September 2026" },
  { id: 11, tag: "NL / EREs", type: "single", roomP: 0.30,
    text: "A barge loads 600 mt fossil naphtha, 200 mt ISCC PLUS circular naphtha and 200 mt ISCC EU bio-naphtha into one tank. The trader discharges 200 mt as circular naphtha at the first port, brings the remaining 800 mt into the Netherlands and applies to book 200 mt of bio-naphtha for EREs, the Dutch renewable-fuel units. Can the full 200 mt be booked?",
    options: ["Yes", "No"], correct: "1",
    source: "NEa, C14-kader ERE" },
  { id: 12, tag: "IR 2022/996", type: "multi", roomP: 0.30,
    text: "The draft revision of Implementing Regulation 2022/996 that was circulated to member states for comments in Q1 2026 includes:",
    options: ["Retroactive cancellation of Proofs of Sustainability (PoS) through the supply chain", "A six-month audit cycle for traders, down from twelve", "A one-month mass-balance period for traders, down from three", "A maximum of three years with the same certification body"], correct: "0123",
    source: "Commission draft revision of IR 2022/996" },
  { id: 13, tag: "Norway", type: "single", roomP: 0.35,
    text: "For its road-fuel blending obligation, Norway currently has transposed the biofuel sustainability criteria of:",
    options: ["RED I (2009)", "RED II (2018)", "RED III (2023)", "Purely national criteria"], correct: "0",
    source: "Produktforskriften kap. 3" },
  { id: 14, tag: "Maritime", type: "single", roomP: 0.30,
    text: "Rapeseed methyl ester is bunkered into a ship. Which of these give it a renewable benefit rather than treating it as fossil?",
    options: ["EU ETS and UK ETS only", "FuelEU Maritime, EU ETS and UK ETS", "EU ETS, UK ETS and the most recent draft of the IMO Net-Zero Framework", "EU ETS, the Dutch ZREs and the most recent draft of the IMO Net-Zero Framework"], correct: "2",
    source: "UK ETS, EU ETS" },
  { id: 15, tag: "Canada", type: "single", roomP: 0.50,
    text: "A biofuel with a carbon intensity of 60 gCO\u2082e/MJ is supplied in British Columbia. The same physical litres can earn credits under both the BC LCFS and Canada\u2019s federal Clean Fuel Regulations.",
    options: ["True", "False"], correct: "0",
    source: "BC LCFR; CFR SOR/2022-140 s. 5" },
  { id: 16, tag: "UK SAF", type: "single", roomP: 0.30,
    text: "A recycled carbon fuel (RCF) SAF has a UK-methodology CI of -35.6 gCO\u2082e/MJ, a 140% saving. Under the UK SAF Mandate, each litre earns:",
    options: ["Nothing", "2 HEFA certificates", "1 Main (non-HEFA) certificate", "2 Main (non-HEFA) SAF certificates"], correct: "3",
    source: "DfT SAF Mandate guidance" },
  { id: 17, tag: "US / RFS", type: "single", roomP: 0.45,
    text: "Under the US RFS, if a Q-RIN (a RIN verified under an EPA-approved Quality Assurance Plan) later proves invalid, the RIN generator has an affirmative defence and the Q-RIN does not need to be replaced.",
    options: ["True", "False"], correct: "1",
    source: "40 CFR 80.1473(b)(3)" },
  { id: 18, tag: "UK / RTFO", type: "single", roomP: 0.30,
    text: "e-Ethanol, an RFNBO, is supplied as marine fuel for a UK domestic voyage. Under the RTFO it earns, per litre equivalent, and under the UK ETS the e-ethanol is treated as:",
    options: ["Nothing / fossil emission factor", "Nothing / zero-rated", "2 dRTFCs / zero-rated", "2 RTFCs / zero-rated"], correct: "3",
    source: "RTFO; UK ETS Authority" },
  { id: 19, tag: "Germany / 37. BImSchV", type: "single", roomP: 0.40,
    text: "Under Germany\u2019s 37. BImSchV intermediate-product pathway, e-methanol used to transesterify FAME has its energy content/carbon savings credited as RFNBO, while the FAME\u2019s CI is calculated as if fossil methanol had been used.",
    options: ["True", "False"], correct: "0",
    source: "\u00a737a(5) Nr. 7 BImSchG" },
  { id: 20, tag: "Germany / THG", type: "single", roomP: 0.25,
    text: "Which of these can currently NOT earn credit under Germany\u2019s THG-Quote after the 2026 amendment of the BImSchG?",
    options: ["e-SAF supplied to German airports", "e-Methanol used as an intermediate in German FAME production", "Green hydrogen used as an intermediate in a German refinery\u2019s fossil-fuel production", "e-Methane supplied as LNG/CNG to international bunkering, with the supplier opting into domestic energy tax"], correct: "0",
    source: "\u00a737a(2) BImSchG (2026)" },
];
export const N_ROUNDS = QUESTIONS.length;
