// type: 'single' (pick one) or 'multi' (select all that apply)
// correct: option indices as a sorted string, e.g. "1" or "01234"
// roomP: expected room accuracy (used only by monkey sizing)
export const QUESTIONS = [
  { id: 1, tag: "US / RFS", type: "single", roomP: 0.85,
    text: "Used cooking oil, as a raw material, can itself be QAP-certified to remove downstream fraud risk of RIN invalidation.",
    options: ["True", "False"], correct: "1" },
  { id: 2, tag: "US / RFS", type: "single", roomP: 0.90,
    text: "Once a producer's Q-RINs are successfully QAP-verified, the producer is protected from upstream supply-chain fraud and the Q-RINs will not be cancelled even if a compliance gap is later identified.",
    options: ["True", "False"], correct: "1" },
  { id: 3, tag: "UK / RTFO", type: "single", roomP: 0.60,
    text: "E-ethanol supplied into UK marine bunkering in a 50/50 blend with fossil methanol generates:",
    options: ["2\u00d7 development RTFCs (dRTFCs)", "2\u00d7 standard RTFCs, on the ethanol volume only", "1\u00d7 standard RTFC on the full blend", "No credit \u2014 marine is out of scope"], correct: "1" },
  { id: 4, tag: "ISCC EU", type: "single", roomP: 0.70,
    text: "You purchase on-spec FAME and detect a fossil additive (<2%). The supplier has issued a PoS for the full delivered quantity. You may book the full delivered quantity into your mass balance as sustainable.",
    options: ["True", "False"], correct: "1" },
  { id: 5, tag: "ISCC EU", type: "multi", roomP: 0.75,
    text: "Which of the following are critical non-conformities?",
    options: ["Issuing a Sustainability Declaration without holding a valid certificate", "Issuing a false or fraudulent Sustainability Declaration", "A negative balance in the mass balance", "Sourcing feedstock from land converted from high-carbon-stock/high-biodiversity status after January 2008", "Denying the auditor access to sites, data, or documentation", "Minor record-keeping/documentation gaps", "Late submission of the annual audit within the permitted cure period"], correct: "01234" },
  { id: 6, tag: "ISCC EU", type: "single", roomP: 0.50,
    text: "In the current draft of IR 2022/996, the mass balance period will be one month, starting 2027.",
    options: ["True", "False"], correct: "0" },
  { id: 7, tag: "Co-processing / NL", type: "single", roomP: 0.75,
    text: "The Netherlands permits taking 100% of the sustainability value of a co-processed batch and allocating it onto a subset of the output volume (leaving the remainder conventional), provided total biogenic energy is conserved.",
    options: ["True", "False"], correct: "1" },
  { id: 8, tag: "Canada", type: "single", roomP: 0.90,
    text: "A biofuel supplied in British Columbia can generate credits under both the BC LCFS and the federal Clean Fuel Regulations simultaneously.",
    options: ["True", "False"], correct: "0" },
  { id: 9, tag: "Canada / CFR", type: "single", roomP: 0.65,
    text: "Under the federal Clean Fuel Regulations, a fuel with carbon intensity 80 gCO\u2082eq/MJ supplied into the diesel pool generates:",
    options: ["Credits", "A compliance obligation (deficit)", "Neither"], correct: "0" },
  { id: 10, tag: "RFNBO electricity", type: "multi", roomP: 0.85,
    text: "Renewable status of the electricity used for RFNBO production can be demonstrated via:",
    options: ["Direct connection to a renewable installation", "A renewable power purchase agreement", "Grid electricity in a bidding zone with >90% renewable share in the previous calendar year", "Grid electricity in a bidding zone with <90% renewable share in the previous calendar year", "Grid electricity in a bidding zone with emission intensity below 18 gCO\u2082eq/MJ, combined with a PPA", "Grid electricity consumed during periods of avoided curtailment / redispatch"], correct: "01245" },
  { id: 11, tag: "RCF", type: "single", roomP: 0.90,
    text: "A fossil waste that is generally recycled into new materials is a good candidate for upgrading into a Recycled Carbon Fuel.",
    options: ["True", "False"], correct: "1" },
  { id: 12, tag: "EU ETS2", type: "single", roomP: 0.80,
    text: "The planned implementation of EU ETS2 was delayed from 2027 to 2028, and the BEHG has been extended accordingly.",
    options: ["True", "False"], correct: "0" },
  { id: 13, tag: "THG-Quote / DE", type: "multi", roomP: 0.35,
    text: "Eligible ways to generate THG-quota RFNBO credit include:",
    options: ["Supplying RFNBOs to the German road market", "Supplying RFNBOs to the German aviation market", "E-fuel supplied into shipping", "Supplying RFNBOs as intermediate to German FAME production", "Supplying RFNBOs as intermediate to German conventional fossil fuel production"], correct: "01234" },
  { id: 14, tag: "THG-Quote / DE", type: "single", roomP: 0.45,
    text: "When e-methanol is used to produce FAME via the intermediate pathway:",
    options: ["A fraction of the FAME will be considered RFNBO", "The FAME will be considered fully bio, with carbon intensity calculated as though fossil methanol were used", "The FAME will be considered fully bio, with the carbon intensity of the e-methanol"], correct: "0" },
  { id: 15, tag: "Ireland", type: "single", roomP: 0.85,
    text: "POME-based HVO supplied into Ireland (post-1 July 2025) generates:",
    options: ["2 certificates/MJ, advanced (Annex IX Part A), no additional certificate", "2 certificates/MJ, advanced, plus the additional HVO certificate", "1 certificate/MJ, no double counting", "2 certificates/MJ, Annex IX Part B"], correct: "0" },
  { id: 16, tag: "Norway", type: "single", roomP: 0.65,
    text: "RED II/III compliance is necessary when supplying fuels into Norway.",
    options: ["True", "False"], correct: "1" },
];
export const N_ROUNDS = QUESTIONS.length;
