# Deterministic build bump: sets ALL build markers by regex and asserts the result.
import re, sys
new = sys.argv[1]
c = open('js/config.js').read()
c2, n1 = re.subn(r'export const BUILD = "[^"]+";', f'export const BUILD = "{new}";', c)
open('js/config.js','w').write(c2)
open('version.json','w').write('{ "build": "%s" }\n' % new)
# Day-by-day additions/deletions/commits from git history, for the wall's build chart.
import subprocess, datetime, collections
try:
    log = subprocess.run(['git', 'log', '--numstat', "--format=COMMIT %ad", '--date=short'],
                         capture_output=True, text=True, check=True).stdout
    days = collections.OrderedDict(); cur = None
    for line in log.splitlines():
        if line.startswith('COMMIT '):
            cur = line.split()[1]; days.setdefault(cur, [0, 0, 0]); days[cur][2] += 1
        elif line and cur:
            parts = line.split('\t')
            if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
                days[cur][0] += int(parts[0]); days[cur][1] += int(parts[1])
    if days:
        first = datetime.date.fromisoformat(min(days)); last = datetime.date.fromisoformat(max(days))
        rows = []
        d = first
        while d <= last:
            k = d.isoformat(); a, dl, n = days.get(k, [0, 0, 0])
            rows.append('  { d: "%s", add: %d, del: %d, n: %d },' % (k, a, dl, n))
            d += datetime.timedelta(days=1)
        open('js/codefreq.js', 'w').write(
            '// Generated by tools_bump.py from git history at each bump. Do not edit.\n'
            'export const CODEFREQ = [\n' + '\n'.join(rows) + '\n];\n')
        print("codefreq: %d days, %d commits" % (len(rows), sum(v[2] for v in days.values())))
except Exception as e:
    print("codefreq: skipped (%s)" % e)

x = open('index.html').read()
x2, n2 = re.subn(r'\?v=[a-z0-9-]+', f'?v={new}', x)
open('index.html','w').write(x2)
assert n1 == 1, "config BUILD line not found"
assert n2 >= 12, f"import map entries: {n2}"
for f, want in (('js/config.js', 1), ('version.json', 1)):
    assert open(f).read().count(new) == want, f
print(f"bumped to {new}: config 1, version 1, map {n2}")
